// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFirstWebApp.Models;

#nullable disable

namespace MyFirstWebApp.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20220809122928_ShopIncome")]
    partial class ShopIncome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.5.22302.2");

            modelBuilder.Entity("MyFirstWebApp.Models.Cashier", b =>
                {
                    b.Property<int>("CashierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CashierName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShopModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CashierId");

                    b.HasIndex("ShopModelId");

                    b.ToTable("Cashiers");
                });

            modelBuilder.Entity("MyFirstWebApp.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShopIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("MyFirstWebApp.Models.Cashier", b =>
                {
                    b.HasOne("MyFirstWebApp.Models.ShopModel", "ShopModel")
                        .WithMany("Cashiers")
                        .HasForeignKey("ShopModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopModel");
                });

            modelBuilder.Entity("MyFirstWebApp.Models.ShopModel", b =>
                {
                    b.Navigation("Cashiers");
                });
#pragma warning restore 612, 618
        }
    }
}
